Repository projectdiscovery/notify, pull requests merged in 2022-06, with the labels that each got.

#147 introduced go.uber.org/ratelimit for rate-limit
  cmd/notify/notify.go
  go.mod
  go.sum
  pkg/utils/throttle.go
Labels: Status: Review Needed, Type: Bug

#141 Add subject customization #118
  README.md
  pkg/providers/smtp/smtp.go
Labels: Status: Review Needed

#150 Rework #146. Fixes various errors relating to input length.
  internal/runner/runner.go
  internal/runner/util.go
Labels: Type: Bug
